import pandas as pd
from sklearn.preprocessing import StandardScaler
from src.feature_engineering import build_features

def load_data(filepath):
    """
    Load raw CSV data and format date column.
    """
    df = pd.read_csv(filepath)
    df['date'] = pd.to_datetime(df['date'])
    return df

def preprocess_and_split(df, split_date="2025-06-01", target_col='sales'):
    """
    Apply feature engineering, drop NaN rows, and split train/test datasets chronologically.
    """
    # 1. Feature Engineering
    df_feat = build_features(df)
    
    # 2. Drop rows with NaNs generated by lags and rolling windows
    df_clean = df_feat.dropna().reset_index(drop=True)
    
    # 3. Chronological Split
    split_dt = pd.to_datetime(split_date)
    train_df = df_clean[df_clean['date'] < split_dt]
    test_df = df_clean[df_clean['date'] >= split_dt]
    
    features = [
        'store', 'item', 'price',
        'year', 'month', 'week', 'day', 'dayofweek', 'quarter', 'is_weekend',
        'sales_lag_7', 'sales_lag_14', 'sales_lag_30',
        'sales_roll_mean_7', 'sales_roll_mean_14', 'sales_roll_mean_30'
    ]
    
    X_train = train_df[features]
    y_train = train_df[target_col]
    X_test = test_df[features]
    y_test = test_df[target_col]
    
    return X_train, y_train, X_test, y_test, features

def scale_features(X_train, X_test):
    """
    Standard scale training and test features.
    """
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)
    return X_train_scaled, X_test_scaled, scaler
